name: CI Students API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      # Test sur Node 20 et Node 22
      matrix:
        node-version: [20.x, 22.x]

    defaults:
      run:
        working-directory: ./student # Emplacement du code NestJS

    steps:
      - name: 1. Checkout (Récupérer le code)
        uses: actions/checkout@v4

      - name: 2. Setup (Configurer Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './student/package-lock.json'

      - name: 3. Install (Installer les dépendances)
        run: npm ci

      - name: 4. Lint (Vérifier la qualité du code)
        run: npm run lint

      - name: 5. Test (Lancer les 15 tests E2E)
        run: npm run test:e2e

      - name: 🧪 Run Tests with Coverage
        run: npm run test:cov # Commande par défaut de NestJS

      - name: 📊 Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: student/coverage/
      